# Generated by Django 4.0.1 on 2022-01-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100, null=True)),
                ('hobby', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raiting', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Okey'), (3, 'Fine'), (4, 'Good'), (5, 'Amaizing')])),
                ('rait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raiting_book', to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertBookRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_selection', to='book.book')),
                ('expert_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.expertbook')),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_comment', models.TextField()),
                ('date_now', models.DateField(auto_now_add=True, null=True)),
                ('book_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='book.book')),
            ],
        ),
    ]
