# Generated by Django 4.0.1 on 2022-01-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiting',
            old_name='rait',
            new_name='book',
        ),
    ]
